# Generated by Django 6.1.1 on 2026-09-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='branches.branch')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='managers.managerprofile')),
            ],
            options={
                'db_table': 'targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='targets.target')),
            ],
            options={
                'db_table': 'target_entries',
                'ordering': ['-date'],
            },
        ),
    ]
