# Generated by Django 6.1.1 on 2026-10-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetentry',
            name='target_amount',
        ),
        migrations.AddField(
            model_name='target',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
