# Generated by Django 6.1.1 on 2026-10-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_remove_targetentry_target_amount_target_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetentry',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=10),
        ),
    ]
