# Generated by Django 6.1.1 on 2026-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_targetentry_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetentry',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=10),
        ),
    ]
