# Generated by Django 6.1.1 on 2026-09-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryexpense',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taxentry',
            name='month',
            field=models.DateField(),
        ),
    ]
