# Generated by Django 6.1.1 on 2026-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_salaryexpense_month_alter_taxentry_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
